name: Continuous Integration

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * 1'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, '3.10']
        sphinx-version: ['>=3.0.0,<4.0.0', '>=4.0.0,<5.0.0', '>=5.0.0,<5.1.0', '>=5.1.0,<6.0.0']
        exclude:
          # Old major version does not support python 3.10
          - python-version: '3.10'
            sphinx-version: '>=3.0.0,<4.0.0'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          architecture: x64
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python tools/fetch_revealjs.py
          pip install ".[test,lint]"
          pip install 'Sphinx${{ matrix.sphinx-version }}'
      - name: Lint sources and doc
        run: |
          black --check .
          flake8 .
          doc8 .
      - name: Run tests
        run: |
          pytest
